# Generated by Django 2.2 on 2020-08-07 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Описание')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Подробное описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('status', models.ForeignKey(choices=[('new', 'Новая'), ('in progress', 'В процессе'), ('done', 'Сделано')], default='new', on_delete=django.db.models.deletion.PROTECT, related_name='task_status', to='webapp.Status', verbose_name='Статус')),
                ('type', models.ForeignKey(choices=[('Task', 'задача'), ('Bug', 'ошибка'), ('Enhancement ', 'улучшение')], default='Task', on_delete=django.db.models.deletion.PROTECT, related_name='task_type', to='webapp.Type', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
