# Generated by Django 2.2 on 2020-08-13 07:00

from django.db import migrations

def transfer_types(apps, schema_editor):
    Task = apps.get_model('webapp.Task')
    for task in Task.objects.all():
        task.type.add(task.type_old)


def rollback_transfer(apps, schema_editor):
    Task = apps.get_model('webapp.Task')
    for task in Task.objects.all():
        task.type_old.set(task.type)

class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200813_0659'),
    ]

    operations = [
        migrations.RunPython(transfer_types, rollback_transfer)
    ]
